### ISSUE TITLE
Pull request to official repo

### ISSUE THREAD

**Issue by dalepo** [mariohmol/ang-jsoneditor#1]
Hey, can you make a pull request to the official repo you forked? Or are you planning on using the library here?

**Comment by mariohmol** [comment]
i can do it.. but the problem with the original one its that it is binded to angular4... (name of repo.. name of npm package...) .. so i just did a generic name.. but the components its the same of the @manishit56

**Comment by mariohmol** [comment]
I will mainting this updated here during the angular changes.  i'm using in production so i need this always up to dated. Anyway, i created the PR https://github.com/manishit56/Angular4-JsonEditor/pull/13
