### ISSUE TITLE
How do we add the options for ace editor using ang-jsoneditor node module. 

### ISSUE THREAD

**Issue by SwapnilChidrawar** [mariohmol/ang-jsoneditor#10]
How do we add the options for ace editor using ang-jsoneditor node module. because  could not see any of my solution is working. i am using latest version of angular that is 6. 

I also wanted to disable the jsoneditor repair option which came in code mode 

here i don't want to use the css to disable that feature

**Comment by mariohmol** [comment]
Hi.. try to follow this:  

* https://github.com/josdejong/jsoneditor/blob/master/docs/api.md#configuration-options

So in ang-jsoneditor will be something like

```
constructor() {
    this.editorOptions = new JsonEditorOptions();
    this.editorOptions.ace = new Ace();
}
```

**Comment by SwapnilChidrawar** [comment]
we created the new instance of editorOptions.ace using new Ace() by importing it from jsoneditor npm module, but then we are getting this error : 

`AppComponent_Host.ngfactory.js? [sm]:1 ERROR TypeError: jsoneditor__WEBPACK_IMPORTED_MODULE_2__.Ace is not a constructor
    at new AppComponent (app.component.ts:18)
    at createClass (core.js:8988)
    at createDirectiveInstance (core.js:8875)
    at createViewNodes (core.js:10095)
    at createRootView (core.js:10009)
    at callWithDebugContext (core.js:11040)
    at Object.debugCreateRootView [as createRootView] (core.js:10527)
    at ComponentFactory_.push../node_modules/@angular/core/fesm5/core.js.ComponentFactory_.create (core.js:8355)
    at ComponentFactoryBoundToModule.push../node_modules/@angular/core/fesm5/core.js.ComponentFactoryBoundToModule.create (core.js:3159)
    at ApplicationRef.push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.bootstrap (core.js:4380)`

**Comment by mariohmol** [comment]
I think you have to use like this

``` 
var textEditor = ace.edit("editorid");
textEditor.setFontSize("11pt");
textEditor.getSession().setMode("ace/mode/toml"); 
```

check this discutission

https://github.com/josdejong/jsoneditor/issues/309

**Comment by SwapnilChidrawar** [comment]
@mariohmol Please let us know that how we can add the options using angular 5to ace editor

**Comment by mariohmol** [comment]
I'm sorry.. i'm not familiar with ace.. if you can make an example doing this custom with normal jsoneditor.. i can try to replicate this to angular

**Comment by jabiinfante** [comment]
Hi @SwapnilChidrawar 
I think #14 might do what you need (or something pretty close to it).

**Comment by mariohmol** [comment]
Hi.. commited one example replacing the Ace Editor and passing this to jsoneditor.. 

https://github.com/mariohmol/ang-jsoneditor/blob/master/src/app/demo/demo.component.ts#L68

but to be honest i dont know how that works on jsoneditor .. you should ask the repo

https://github.com/josdejong/jsoneditor
