### ISSUE TITLE
Update to Latest Angular

### ISSUE THREAD

**Issue by Stankman** [mariohmol/ang-jsoneditor#104]
Please update this package to latest Angular, would be awesome.

**Comment by mariohmol** [comment]
@hardikpatel043  could you help on that?

**Comment by RodolfoXDR** [comment]
+1

**Comment by mariohmol** [comment]
@ShaneDFields do you wanna try this?

**Comment by ShaneDFields** [comment]
> @ShaneDFields do you wanna try this?

Sure thing!

**Comment by mariohmol** [comment]
released on v3.0.0, thanks a lot @hardikpatel043
