### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by famcoo** [mariohmol/ang-jsoneditor#105]
ReferenceError: self is not defined
    at Object.21310(......)
    ......

**Comment by mariohmol** [comment]
Hi there.. could you please provide the full stack trace or an example to reproduce this error?

Please feel free to reopen when u get back

**Comment by marian-toaderr** [comment]
this is still an issue when using SSR/SSG.

**Comment by leonwissenberg** [comment]
@marian-toaderr did you find any workaround?
