### ISSUE TITLE
When mode is code or text，it can be modified fully？

### ISSUE THREAD

**Issue by MichaelPanwenjie** [mariohmol/ang-jsoneditor#106]
When mode is “code” or ”text”，it can be modified fully， you can insert，delete，modify everythings with no limit
I think if can set operating with limit such as partial modify，none deleting，non inserting which can set by your willing， that will be better。

Can you update the component ？

**Comment by mariohmol** [comment]
Uhm, I guess this feature might be asked in the https://github.com/josdejong/jsoneditor project.
If you know how we could implement this just in this wrapper, please let us know
