### ISSUE TITLE
Support Angular 15

### ISSUE THREAD

**Issue by trentprynn** [mariohmol/ang-jsoneditor#109]
**Is your feature request related to a problem? Please describe.**
Angular v15 has been released, it would be great if this library could officially support the newest version

**Describe the solution you'd like**
Angular v15 is officially supported

**Comment by foka** [comment]
Version `1.10.5` works fine on Angular 15.
```
npm i ang-jsoneditor@1.10.5
```

**Comment by trentprynn** [comment]
angular 15 is supported, closing

**Comment by jtomek** [comment]
No, the problem persists on the latest version. 

I can confirm, though, that v1.10.5 works on Angular 15.
