### ISSUE TITLE
Getting data from separate editors on the same page.

### ISSUE THREAD

**Issue by Tih1st** [mariohmol/ang-jsoneditor#11]
I have a page where I am using two JSON editors at the same time, but I want to be able to use editor.get() to get data from editor 1 and editor 2 respectively. Is there a way to do this in angular 5?

**Comment by mariohmol** [comment]
Try this:    


``` html
<json-editor #editorOne >
<json-editor #editorTwo >
```

TS: 

```
export class MyComponent {
editorExample;
getData(){
this.editorOne.get();
this.editorTwo.get();
}
}

```

**Comment by Tih1st** [comment]
Tried your code above;
My HTML:
`<json-editor #editorOne [options]="editorOptions" [data]="data" ></json-editor>
    <br>
    <json-editor #editorTwo [options]="editorOptions" [data]="data" ></json-editor>`

My TS:
```
export class Page3Component {
  public editorOptions: JsonEditorOptions;
  public data: any;
  @ViewChild(JsonEditorComponent) editor: JsonEditorComponent;


  editorOne;
  editorTwo;
...
}
```
Trying `this.editorOne.get()` in the debug console gives me `TypeError: Cannot read property 'get' of undefined` so it seems the editors are not being recognized as JSON editor components

**Comment by mariohmol** [comment]
Try this `@ViewChild(JsonEditorComponent) editorOne: JsonEditorComponent;`

**Comment by Tih1st** [comment]
```
@ViewChild(JsonEditorComponent) editorOne: JsonEditorComponent;
@ViewChild(JsonEditorComponent) editorTwo: JsonEditorComponent;
```
this.editorTwo.get() gives me the contents of editor one 

I also tried putting it into the constructor 
```
constructor(private appService: AppService) {
      this.editorOptions = new JsonEditorOptions()
      this.editorOptions.modes = ['code', 'text', 'tree', 'view']; // set all allowed modes
      this.editorOptions.mode = 'text'; //set only one mode
      this.editorOne = new JsonEditorComponent;
      this.editorTwo = new JsonEditorComponent;
     }
```
but I still get the contents of editor one everytime

**Comment by mariohmol** [comment]
This will work
```
  @ViewChild('editorOne') editorOne: JsonEditorComponent;
  @ViewChild('editorTwo') editorTwo: JsonEditorComponent;
```

i included this example in the demo app.. thanks
