### ISSUE TITLE
TypeError: (jsoneditor__WEBPACK_IMPORTED_MODULE_0___namespace_cache || jsoneditor__WEBPACK_IMPORTED_MODULE_0___namespace_cache) is not a constructor

### ISSUE THREAD

**Issue by trashersmashercoolguy** [mariohmol/ang-jsoneditor#113]
Got an error at version 2.0.0.  at 1.10.5 everything is fine
TypeError: (jsoneditor__WEBPACK_IMPORTED_MODULE_0___namespace_cache || jsoneditor__WEBPACK_IMPORTED_MODULE_0___namespace_cache) is not a constructor
    at JsonEditorComponent.ngOnInit (ang-jsoneditor.mjs:71:23)
    at callHook (core.mjs:2491:22)
    at callHooks (core.mjs:2460:17)
    at executeInitAndCheckHooks (core.mjs:2411:9)
    at refreshView (core.mjs:11971:21)
    at refreshComponent (core.mjs:13030:13)
    at refreshChildComponents (core.mjs:11746:9)
    at refreshView (core.mjs:12006:13)
    at refreshEmbeddedViews (core.mjs:12984:17)
    at refreshView (core.mjs:11980:9)

**Comment by RodolfoXDR** [comment]
It doesnt work on latest Angular

**Comment by teamz-marcos** [comment]
It seems like doesn't work in angular 12

**Comment by lhqmcy** [comment]
It's all the same to me.

**Comment by meenalgupta23** [comment]
any update about it? I'm also getting the same issue

**Comment by martinpeterek** [comment]
Any updates with updating to latest version of angular?

**Comment by faraz-ahmad-uft** [comment]
I am getting the same error when I upgraded it to 2.0.0. Is there any solution of this error?

**Comment by john8329** [comment]
Yup same. Package is unmaintained as of today.

**Comment by JuamBer** [comment]
Same issue here with this config:

Angular CLI: 15.1.4
Node: 18.12.1
Package Manager: npm 8.19.2
OS: win32 x64

**Comment by ssougnez** [comment]
I don't have time for a PR but the author just needs to update its json-editor import in:

`import editor from 'jsoneditor';`

And this will work.

**Comment by mariohmol** [comment]
Thanks @ssougnez, will give it a try now

**Comment by faraz-ahmad-uft** [comment]
@mariohmol  Any update on this?

**Comment by mariohmol** [comment]
released on v3.0.0, thanks a lot!
