### ISSUE TITLE
'NgJsonEditorModule' does not appear to be an NgModule class.

### ISSUE THREAD

**Issue by kkovac1** [mariohmol/ang-jsoneditor#117]
**Describe the bug**
This error (down below) appeared when updated Angular to version 16.  Worked fine on version 15.

ang-jsoneditor version: 1.10.5

Error: 
_'NgJsonEditorModule' does not appear to be an NgModule class.(-996002)
lib.module.d.ts(2, 32): This likely means that the library (ang-jsoneditor) which declares NgJsonEditorModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy._

**Comment by mariohmol** [comment]
released on v3.0.0,thanks a lot!
