### ISSUE TITLE
It is impossible to build v3.1.1 with Angular v14, however version 3.1.0 builds fine

### ISSUE THREAD

**Issue by tscislo** [mariohmol/ang-jsoneditor#130]
NgJsonEditorModule
is properly imported in module, but during build time I got an error like the component does not exist:
"Can't bind to 'debug' since it isn't a known property of 'json-editor'"

This only happens on version 3.1.1, not with 3.1.0

**Comment by mariohmol** [comment]
hi there..
do you have a full stack trace? where is this error thoring? which line or file?

thanks

**Comment by mariohmol** [comment]
Try v4.x
