### ISSUE TITLE
How does one set the theme?

### ISSUE THREAD

**Issue by matthew-g-austin** [mariohmol/ang-jsoneditor#131]
How do you set the theme? The theme option in the editoroptions is a number type. What are the possible values? I get a blank editor if I set it to anything other than 0. Is there a way to set the theme to one of the Ace supported themes?

**Comment by mariohmol** [comment]
Hi there, thats a good question. 
I've never used the teme option, and this warpper basically pass the theme to the root component 

Maybe for the custom styling try to get some example for the jsoneditor component?

https://github.com/josdejong/jsoneditor/blob/develop/examples/06_custom_styling.html

if u have some working example with themes and native jsoneditor, and it doesnt work in this wrapper.. please reopen the ticket
