### ISSUE TITLE
Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.

### ISSUE THREAD

**Issue by SeKutai** [mariohmol/ang-jsoneditor#134]
I have an error inside of jsoneditor.component.ts that says 
```Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.ts(2707)```
the line that is giving the error is:
```typescript
static ɵcmp: i0.ɵɵComponentDeclaration<JsonEditorComponent, "json-editor", never, { "options": { "alias": "options"; "required": false; }; "debug": { "alias": "debug"; "required": false; }; "data": { "alias": "data"; "required": false; }; }, { "change": "change"; "jsonChange": "jsonChange"; }, never, never, false, never>;
```
![err](https://github.com/mariohmol/ang-jsoneditor/assets/107933316/c1deee05-5dc0-4c10-a0ec-c7a2c3170111)

I might have installed ang-jsoneditor wrong but am not sure of what I may have missed

I am using:
Angular CLI: 14.1.0
Node: 16.15.1
Package Manager: npm 8.11.0
OS: win32 x64
Browser: Microsoft Edge for Business Version 120.0.2210.133

**Comment by SeKutai** [comment]
Sorry this was actually and issue with jsoneditor my bad.

**Comment by SeKutai** [comment]
Sorry this was actually and issue with jsoneditor my bad.

**Comment by mariohmol** [comment]
THanks for letting us know
