### ISSUE TITLE
Support for Angular 16 & 17?

### ISSUE THREAD

**Issue by samantha-swift** [mariohmol/ang-jsoneditor#135]
Our business currently uses this tool and it is amazing. With a recent upgrade to angular 17 the editorOptions are no longer appearing. Is there support for angular 16/17 coming soon or is there anything I can do to fix the options?

**Comment by BartjeD** [comment]
@mariohmol I am also interested in this

**Comment by BartjeD** [comment]
We ended up switching to `vanilla-jsoneditor`, which was bascially a drop-in replacement for this plugin.

**Comment by mariohmol** [comment]
please try v4.0.0
