### ISSUE TITLE
special characters throwing the exception

### ISSUE THREAD

**Issue by satishankam** [mariohmol/ang-jsoneditor#140]
ang-jsoneditor is throwing the exception like 'istrusted = true' when entered the special characters like = '',' etc in the editor. what would be the remedy for this?

**Comment by satishankam** [comment]
> ang-jsoneditor is throwing the exception like 'istrusted = true' when entered the special characters like = '',' etc in the editor. what would be the remedy for this?

Ignore this request

**Comment by satishankam** [comment]
problem resolved by using the reference variable 'get' method.,

**Comment by mariohmol** [comment]
thanks for letting us know
