### ISSUE TITLE
jsoneditoroptions.ts needs to be synced up with native jsoneditor 

### ISSUE THREAD

**Issue by Jgrochmal** [mariohmol/ang-jsoneditor#141]
**Is your feature request related to a problem? Please describe.**
jsoneditoroptions.ts is missing options that are present in jsoneditor such as limitDragging

**Describe the solution you'd like**
Implement all options available in native jsoneditor

**Describe alternatives you've considered**
none

**Additional context**

**Comment by mariohmol** [comment]
Added on ang-jsoneditor@4.0.1 thanks

if u have a list of missing ones lets us know
