### ISSUE TITLE
Update dependencies to jsoneditor 10.x.x

### ISSUE THREAD

**Issue by bizappzone** [mariohmol/ang-jsoneditor#142]
Currently if you upgrade jsoneditor to 10.x.x we get a dependency error of  peer jsoneditor@"^9.10.2" from ang-jsoneditor@3.1.1

**To Reproduce**
 npm i jsoneditor ang-jsoneditor

**Expected behavior**
Dependencies should be updated

**Console and Error stack trace**
 jsoneditor@"^10.0.3" from the root project
npm WARN   1 more (ang-jsoneditor)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer jsoneditor@"^9.10.2" from ang-jsoneditor@3.1.1
npm WARN node_modules/ang-jsoneditor
npm WARN   ang-jsoneditor@"^3.1.1" from the root project

**Screenshots**

**Comment by mariohmol** [comment]
added on ang-jsoneditor@4.0.1
