### ISSUE TITLE
Editor loses focus if data is changed and displayed

### ISSUE THREAD

**Issue by MarcusRiemer** [mariohmol/ang-jsoneditor#15]
I would like to reflect changes on the fly (e.g. as soon as the user changes something). But every time I change something in the `code` or the `tree` view, the jsoneditor loses focus. This issue can be replicated in the sample code by adding `this.data = JSON.parse(this.editor.getText())` in the `change`-callback.

I suspect this happens because Angular re-renders the view and destroys the jsoneditor in that process. But would there be any way to work around this?

Edit (after further investigation): Its far more then the editing state that is lost on changes. The previously selected mode is lost as well and the current expansion state is lost as well. It seems that the editor is resetted entirely .

**Comment by mariohmol** [comment]
Hi!
Thanks for reporting this.. 

Can u please use this link and check if this behaviour happens?

https://stackblitz.com/edit/angular-json-editor?file=src%2Fapp%2Fapp.component.ts

**Comment by MarcusRiemer** [comment]
Sure, I forked your example and added the assignment: https://stackblitz.com/edit/angular-json-editor-uodqc5

And just to make sure that we are talking about the same thing:
![A quick screencast to show what happens](https://user-images.githubusercontent.com/2138773/43639111-72c11ace-971b-11e8-8645-93adbc6f28e2.gif)

I am fully aware that it is impossible to automatically do much about the changing data itself: If the bound data changes there may be any number of conflicts that can't be resolved automatically. I do **not** expect any meaningful cursor position or expansion state if the bound data changes randomly! This is basically the same scenario a text editor is in when it detects that the edited file has changed on disk. And it resolves that by asking the user what to do: "Keep the state from the editor" or "Reload from disk"? Imho this kind of logic is far outside the scope of this neat little wrapper.

But maybe it would be possible to somehow preserve some state like the previous position of the cursor and the selected mode? At least for minor edits this should do the trick.

**Comment by mariohmol** [comment]
Gotcha!

My question is.. why you need to change the data? If you need to save this on database, just call the ajax, or if you need that in another component, you can call a event or service to pass it on

Because the problem here is to update the same data you used to build the jsoneditor

**Comment by MarcusRiemer** [comment]
I use the editor as a (weak) excuse to postpone some "real" UI writing (screenshot 2 and 3). The edited data models are quite complex, so building their UI simply takes a while. Having some kind of two way databinding allows loads of experimentation: You can change the model from the (only partially finished) UI and from the editor.

As I said: I wouldn't expect the actually edited data to survive or to get merged. But I would love to see "trivial" parts the editor state preserved when changing the data. Currently even if I only "write back" the data selectively (shown in the first screenshot) things like the selected mode are lost.

**Screenshot 1:** Selective update, asking the user "Data has changed, which version do you prefer?"
![screenshot_20180803_161609](https://user-images.githubusercontent.com/2138773/43647673-aa11676e-9738-11e8-9719-b80b339a28a7.png)

**Screenshot 2:** Hardly any UI at all, only a JSON-editor
![Hardly any UI at all](https://user-images.githubusercontent.com/2138773/43647164-1d8c5638-9737-11e8-991d-2c61a2c143f7.png)

**Screenshot 3:** A little UI, but still a JSON-editor
![A little UI](https://user-images.githubusercontent.com/2138773/43647186-2d8b8586-9737-11e8-9e00-297dcd35ad84.png)

**Comment by mariohmol** [comment]
Thanks!!

I think i got a solution for you, check version 1.6.2.. if is not working as expected please reopen
