### ISSUE TITLE
Local json file data 

### ISSUE THREAD

**Issue by butaninilesh** [mariohmol/ang-jsoneditor#18]
Hi,
I have download code here and demo code is working fine.
But, I have faced issue, when I load json data from local directory and load to JSOn editor.

 jsonRead(): void{
    this.demoservice.getConfig().subscribe(d => {
      this.data = d;
      this.changeData();
      console.log(this.data);
    });
  }

Updated json data is not reflected in json editor template.

Can you please give a solution for the same?

Thanks,
Nilesh.

**Comment by mariohmol** [comment]
How is this `d`? Is a string? is not missing JSON.parse?

try to do `this.data= { test: true } ` and see if the jsoneditor show this data

**Comment by butaninilesh** [comment]
jsonRead(): void{
    this.demoservice.getConfig().subscribe(d => {
      this.data = { test: true };
      this.changeData();
      console.log(this.data);
    });
  }
I have attach image file here.Please verify editor as well as browser console for the same.

![demo editor data](https://user-images.githubusercontent.com/42807795/44828955-e205a680-ac37-11e8-9532-9d89a92a9399.png)

**Comment by mariohmol** [comment]
Hi, could u figure it out?

**Comment by mariohmol** [comment]
Hi.. i'm closing for now.. if u still with this issue please come back so we can figure it out
