### ISSUE TITLE
onchange causes many console.errors!

### ISSUE THREAD

**Issue by phil1996s** [mariohmol/ang-jsoneditor#19]
Hey, 

I've use the onchange method to validate keys with my custom regex:

````javascript
this.editorOptions.onChange = () => {
      this.validateJson(this.schemaEditor.get(), 'schemaErrorMessages');
};
````

But whenever I use the "onchange"-Method there are many errors thrown into the console while typing. I have also tested in in your stackblitz demo there it has the same functionality.

![bildschirmfoto 2018-09-10 um 11 35 20](https://user-images.githubusercontent.com/17291660/45289550-bfa04280-b4ed-11e8-86a8-a9ccbaafe55f.png)

**Comment by phil1996s** [comment]
But I did not get the errors if I didn't use the change method. 
It would be much better if we can set a prop for the json-editor not to log own validation errors.

**Comment by phil1996s** [comment]
Fixed by using 
````javascript
this.editorOptions.onChange = () => {
      try {
          this.validateJson(this.schemaEditor.get(), 'schemaErrorMessages');
      } catch {}
};
````

**Comment by greatsayan** [comment]
Hi,
I'm still facing this issue... How can I fixed that? I'm able to reproduce that on Stackblitz. (https://stackblitz.com/edit/ang-jsoneditor)
I see that the plugin is not up to date with jsoneditor (8.2.0 now) and couple of issues were fixed. Is it possible to updated your package to use the latest version of jsoneditor?
Thanks a lot!

**Comment by mariohmol** [comment]
this is updated to 8.3.0 .. can u double check please? if still an issue please reopen
