### ISSUE TITLE
<json-editor> is not recognised

### ISSUE THREAD

**Issue by asheikabrar** [mariohmol/ang-jsoneditor#20]
In my html i am using like this 
    <json-editor [options]="editorOptions" [data]="data">

    </json-editor>

complains as unknown tag 

using angular 6

**Comment by mariohmol** [comment]
Hi. this seems to be missing the module..

try to follow this https://stackblitz.com/edit/angular-json-editor

maybe you need this step?

``` 
import { NgJsonEditorModule } from 'ang-jsoneditor' 

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    ....,
    NgJsonEditorModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }  
```

**Comment by asheikabrar** [comment]
thanks  
i have followed the step but no error is thrown but at the same time editor is also not displayed do we really need to have schema for this editor to work .
confused what  might be going wrong

**Comment by mariohmol** [comment]
Try to make this code in stackblitz replicating the problem.. so we will be able to help u

Following this or make one from scratch.

https://stackblitz.com/edit/angular-json-editor

**Comment by mariohmol** [comment]
Hi, could u figure it out?

**Comment by asheikabrar** [comment]
Yes solved it

**Comment by mariohmol** [comment]
Thanks... if u can share with us what u did.. might help others in the feature!

Thanks
