### ISSUE TITLE
onError not working?

### ISSUE THREAD

**Issue by kojilab** [mariohmol/ang-jsoneditor#21]
Hi,
I'm trying to attach a method on onError but even though the editor shows the error icon it doesn't get called at all. 
Thanks

**Comment by mariohmol** [comment]
Hi! Thanks for sharing this! Do you have an example of code or the error is getting here?

**Comment by mariohmol** [comment]
Hi.. as soon as u get more infor please reopen this

**Comment by icodenerd** [comment]
@mariohmol , I was able to reproduce what kojilab mentioned. Here's my quick example:

private initEditorOptions(editorOptions) {
    editorOptions.modes = ['code', 'view']; // set all allowed modes
    editorOptions.mode = 'code'; // set default mode
    editorOptions.schema = RTD_SUMMARY_SETTINGS_SCHEMA;

    editorOptions.onChange = () => {
      this.canSaveSettings = this.jsonEditor.isValidJson();
    };

    editorOptions.onError = this.onCaughtError;
  }

  private onCaughtError(error: any){
    console.log(error);
  }

Please let me know if there's something I am overlooking

**Comment by mariohmol** [comment]
Isnt this about validation? so using `onValidate` instead?

**Comment by mariohmol** [comment]
isnt this related? https://github.com/josdejong/jsoneditor/issues/306

**Comment by icodenerd** [comment]
> Isnt this about validation? so using `onValidate` instead?

I am actually trying to find the way to get the error type, either warning or error but I have no success thus far. I was hoping the onError property would provide me such a way. Any advice would be helpful.

**Comment by mariohmol** [comment]
I see.. if u can find a doc in jsoneditor or example taking more details about the json validate.. let me know that we can incorporate here
