### ISSUE TITLE
Add unit-test example

### ISSUE THREAD

**Issue by Jiehong** [mariohmol/ang-jsoneditor#22]
Hi,

Perhaps adding a unit-test example would be very nice as well!

**Comment by mariohmol** [comment]
Hi!

Thanks for getting in touch..

For unit test we have just the basic one:

https://github.com/mariohmol/ang-jsoneditor/blob/master/ang-jsoneditor/src/jsoneditor/jsoneditor.component.spec.ts

But we have more tests as e2e:

https://github.com/mariohmol/ang-jsoneditor/tree/master/e2e

Is any specific test you would like to have as an example? If i make it.. are u up to make some new test cases to help out?

thanks!

**Comment by mariohmol** [comment]
Hi!

Added the travis integration, base e2e and unit test running there!

thanks!

**Comment by mariohmol** [comment]
How works the unit test in stackblitz? i'm kind lost

**Comment by Jiehong** [comment]
@mariohmol : sorry, I saw the tests in the repository. They aren't just on the StackBlitz example. My bad.
