### ISSUE TITLE
Missing mainMenuBar option

### ISSUE THREAD

**Issue by vrockai** [mariohmol/ang-jsoneditor#25]
`navigationBar` and `statusBar` are inside the options class definition, but the `mainMenuBar` is missing:
https://github.com/mariohmol/ang-jsoneditor/blob/e3da72b11c1cfa10cf611d7c9373b6d437a1d6e2/ang-jsoneditor/src/jsoneditor/jsoneditor.component.ts#L205

**Comment by mariohmol** [comment]
Hi.. can u make a PR? thanks

**Comment by vrockai** [comment]
sure thing!

**Comment by mariohmol** [comment]
included in v 1.7.2

thanks a lot @vrockai !!
