### ISSUE TITLE
Add an option to automatically expand all nodes

### ISSUE THREAD

**Issue by vrockai** [mariohmol/ang-jsoneditor#26]
This is a feature request to have an option to have the json tree expanded by default.

**Comment by mariohmol** [comment]
Thanks! Do they have a flag for this in jsoneditor?

**Comment by vrockai** [comment]
they don't, they have this issue opened for a long time though:
https://github.com/josdejong/jsoneditor/issues/333

The implementation should be trivial, I can file a PR if you don't mind.

**Comment by mariohmol** [comment]
oww yeah.. if you can make a PR with this working we can do it!

**Comment by mariohmol** [comment]
included in v 1.7.2

thanks a lot @vrockai !!

**Comment by vrockai** [comment]
thanks for accepting my changes, it's much easier than creating a new fork just for this :) so it's already published?

**Comment by mariohmol** [comment]
yes it is.. please help out more.. feel free =)
