### ISSUE TITLE
TS6059: File '../node_modules/ang-jsoneditor/index.ts' is not under 'rootDir'

### ISSUE THREAD

**Issue by dnannaware** [mariohmol/ang-jsoneditor#3]
I am using Angular4JsonEditor in my angular application. Now we are migrating to Angular5, however angular5 jsoneditor is failing with below given errors. Do you have any solution?

TS6059: File '../node_modules/ang-jsoneditor/index.ts' is not under 'rootDir' 'C:\GitRepos\angular5project1\src'. 'rootDir' is expected to contain all source files.

    at Object.<anonymous> (C:\GitRepos\ppc-admin-module\node_modules\ng-packagr\lib\ngc\compile-source-files.js:69:35)
    at Generator.next (<anonymous>)
    at C:\GitRepos\ppc-admin-module\node_modules\ng-packagr\lib\ngc\compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\GitRepos\ppc-admin-module\node_modules\ng-packagr\lib\ngc\compile-source-files.js:3:12)
    at Object.compileSourceFiles (C:\GitRepos\ppc-admin-module\node_modules\ng-packagr\lib\ngc\compile-source-files.js:19:12)
    at Object.<anonymous> (C:\GitRepos\ppc-admin-module\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:20:60)
    at Generator.next (<anonymous>)
    at C:\GitRepos\ppc-admin-module\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)

**Comment by mariohmol** [comment]
What version you are using? Here version `"ang-jsoneditor": "1.5.9",`  is working here

**Comment by dnannaware** [comment]
I am also using "ang-jsoneditor": "1.5.9"

**Comment by mariohmol** [comment]
what is your TS version?
`tsc --version`

**Comment by dnannaware** [comment]
"typescript": "2.2.2"

**Comment by mariohmol** [comment]
My global typescript is 2.6.2 .. try `npm i -g typescript@2.6.2`

**Comment by dnannaware** [comment]
Possible fix looks like as mentioned on angular cli here
https://github.com/angular/angular-cli/wiki/stories-third-party-lib

**Comment by mariohmol** [comment]
If you have an idea how to fix this in code.. please send a PR that we can put it online..

i published a new version 1.5.12 with one fix that maybe will work in your case..

but try it with global typescript to be 2.6.x before u go

**Comment by dnannaware** [comment]
I am not able to install ang-jsoneditor version 1.5.12, getting below given error:

C:\module>npm i ang-jsoneditor/1.5.12 --save
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/ang-jsoneditor/1.5.12.git
npm ERR!
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nsadmin\AppData\Roaming\npm-cache\_logs\2018-03-09T19_48_44_784Z-debug.log

**Comment by mariohmol** [comment]
This should be in your package json `"ang-jsoneditor": "1.5.12",` , its working here in my side as well.

this error u showed now seems to be in your network or something

**Comment by dnannaware** [comment]
I was able install "ang-jsoneditor": "1.5.12" after deleted local npm package. Also I had to explicitly install jsoneditor@^5.14.0.

Now I am not getting the build error I had mentioned earlier.

**Comment by dnannaware** [comment]
I got the "ang-jsoneditor": "1.5.12". Now the issue mentioned is fixed when I run 
**npm run build**
But when I start the application getting the issue is repro
**npm start**

**Comment by dnannaware** [comment]
I have passed the earlier mentioned issue, however facing below mentioned error after run of **npm start** command

ERROR in ./src/lib/admin.module.tsModule not found: Error: Can't resolve 'C:\GitRepos\admin-module\dev\node_modules\ang-jsoneditor' in 'C:\GitRepos\admin-module\src\lib'

**Comment by dnannaware** [comment]
Thanks for your quick replys, issue is resolved now. Installing 1.5.12 npm package and also I had to modify tsconfig.json with below value:
		"paths": {
      		"ang-jsoneditor": [ "node_modules/ang-jsoneditor" ]
    	}

Also I had to update tsconfig.app.json with the path for ang-jsoneditor:
		"paths": {
			"ang-jsoneditor": [ "../node_modules/ang-jsoneditor"]
		}

**Comment by mariohmol** [comment]
where is this? could not find where to fix

**Comment by dnannaware** [comment]
These are the additional changes I had to make in my code.

**Comment by mariohmol** [comment]
Its weird caus ein the app i use it i dont have that conf in my tsconfig.app.ts and it works.. did u tested to just delete this line and see if that still working?
