### ISSUE TITLE
How can we integrate XML reading in addition to JSON?

### ISSUE THREAD

**Issue by mohDev78** [mariohmol/ang-jsoneditor#32]
Hello , i want to read JSON data and XML data .
Can we parse the XML so that it is readable in JSON editor?
thank you

**Comment by mariohmol** [comment]
sorry but this is out of scope.. i think u need another component to convert the XML into JSON and then pass it to jsoneditor

check this out .. https://github.com/josdejong/jsoneditor/issues/245
