### ISSUE TITLE
The expandAll option triggers warnings in the console

### ISSUE THREAD

**Issue by vrockai** [mariohmol/ang-jsoneditor#34]
This was probably introduced with my `expandAll` PR, I don't understand how did I miss it. The console warning doesn't cause any functional issue and looks like this:
![image](https://user-images.githubusercontent.com/1726340/54912223-7b581b00-4ef0-11e9-81b7-6ae49a31a6b9.png)

I'm about to file a PR.

**Comment by mariohmol** [comment]
in favor of #35

**Comment by vrockai** [comment]
@mariohmol it seems you've already published the package a day ago, but I can't see the changes regarding this issue in the published code. Just wondering if there could have been an issue during publishing. Thanks for the info.

In other words, after installing `ang-jsoneditor@1.7.4`, I cannot grep the newly added `optionsCopy` variable:

```
vrockai@vrockai-desktop:/tmp/foo/∂ npm i ang-jsoneditor
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ang-jsoneditor@1.7.4 requires a peer of @angular/core@>=6.0.0-rc.5 but none is installed. You must install peer dependencies yourself.
npm WARN ang-jsoneditor@1.7.4 requires a peer of @angular/common@>=6.0.0-rc.5 but none is installed. You must install peer dependencies yourself.
npm WARN ang-jsoneditor@1.7.4 requires a peer of jsoneditor@^5.19.0 but none is installed. You must install peer dependencies yourself.
npm WARN foo@1.0.0 No description
npm WARN foo@1.0.0 No repository field.

+ ang-jsoneditor@1.7.4
added 2 packages from 2 contributors and audited 2 packages in 0.455s
found 0 vulnerabilities

vrockai@vrockai-desktop:/tmp/foo/∂ ls
node_modules  package.json  package-lock.json
vrockai@vrockai-desktop:/tmp/foo/∂ grep 'optionsCopy' * -R
vrockai@vrockai-desktop:/tmp/foo/∂
```
