### ISSUE TITLE
Make validateSchema method accessible

### ISSUE THREAD

**Issue by maxr96** [mariohmol/ang-jsoneditor#36]
Hi,

I am using JSON Editor to validate JSON against the schema and I need to disable "Save" button in case when either JSON is not valid or JSON doesn't match the schema. In first case I simply check by getting JSON, but for second I need to use **validateSchema** method that accepts JSON object and checks if it matches the schema. This method is however unavailable, so I had to use any typing for **JsonEditorComponent** to access private editor property and call **validateSchema** method on it. Can you, please, add it?

**Comment by mariohmol** [comment]
can u make a PR?

**Comment by mariohmol** [comment]
published on 1.7.5
