### ISSUE TITLE
Gives empty json in 'code' mode if we have more than one editor in same page

### ISSUE THREAD

**Issue by customfitai** [mariohmol/ang-jsoneditor#37]
When we have more than one editor on the same page, the value fetched for all except the first one is empty.

**Comment by mariohmol** [comment]
Updated the stackbliz example

https://stackblitz.com/edit/ang-jsoneditor

And the demos has this as well..
https://github.com/mariohmol/ang-jsoneditor/tree/master/src/app/demo

thanks
