### ISSUE TITLE
Not able to update json if there are multiple JSONeditor

### ISSUE THREAD

**Issue by ankurtechelogy** [mariohmol/ang-jsoneditor#40]

**Comment by mariohmol** [comment]
Hi.. can u describe more this issue?

the demo is working with 2 json editors with no issues

https://stackblitz.com/edit/ang-jsoneditor

**Comment by mariohmol** [comment]
if u still have this issue... let us know

**Comment by osmanraifgunes** [comment]
I have the same problem. If the there is multiple editors (creted by ng-for loop) the events are not firing correctly.

Always first editors parameters are passed.

**Comment by mariohmol** [comment]
please provide an stackblitz code or something to test this behavuour?

**Comment by mariohmol** [comment]
Hi.. @osmanraifgunes with the #58 fixes this issue? can u make a demo with this behaviour so we can fix that?
thanks!

**Comment by osmanraifgunes** [comment]
Here is the example : https://stackblitz.com/edit/ang-jsoneditor-easjts?file=src/app/app.component.html

**Comment by mariohmol** [comment]
thanks for that info!!

what u mean about working as singleton?

do u have any ideas how to fix this?

**Comment by mariohmol** [comment]
The thing here is about reusing the same editorOptions..

in you case what i did to fix was:

```html
<json-editor [options]="makeOptions()" [data]="prd" (change)="showJson($event)"></json-editor>
```


```ts
  makeOptions = () => {
    return new JsonEditorOptions();
  }
```

**Comment by osmanraifgunes** [comment]
Solution is using @ViewChildren instead of @ViewChild. I asked this on stackof : https://stackoverflow.com/questions/60040466/angular-component-multiple-instance-binding-input-problem

But doing so is writing this module whole again.

**Comment by mariohmol** [comment]
I included this solution in the docs and in the demo app as well.. see if that works in your side

**Comment by SahilMahadwar** [comment]
Hi how can we add options when we use 
makeOptions = () => {
    return new JsonEditorOptions();
  }

**Comment by mariohmol** [comment]
Hi you can add this way.

Just updated the docs with it

```
makeOptions = () => {
  const options = new JsonEditorOptions();
  options.modes = ['code', 'text', 'tree', 'view'];
  return options;
}
```
