### ISSUE TITLE
Issues with javascript library?

### ISSUE THREAD

**Issue by LanceJensen-Teradata** [mariohmol/ang-jsoneditor#41]
Hello. I am having difficulty using your angular component and it is likely due to my ignorance since I have really only used angular 2 in the past.  I am recieving exceptions in the console.  I have some theories but I would really appreciate some help. When I run your demo project I do not have problems however when I import the module and use it in a second project I get the error message below:

compiler.js:215 Uncaught Error: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'json-editor'.
1. If 'json-editor' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'json-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("com/mariohmol/ang-jsoneditor/blob/master/src/app/demo/demo.component.html -->
        	<json-editor [ERROR ->][options]="editorOptions" [data]="dataSetJson" #editor></json-editor>
            
        	<json-editor [options]="editorOptions" [ERROR ->][data]="dataSetJson" #editor></json-editor>
            
        	[ERROR ->]<json-editor [options]="editorOptions" [data]="dataSetJson" #editor></json-editor>
            <!-- <"): ng:///SharedModule/CustomDatasetComponent.html@24:9
    at syntaxError (compiler.js:215)
    at TemplateParser.push../node_modules/@angular/compiler/fesm5/compiler.js.TemplateParser.parse (compiler.js:14702)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._parseTemplate (compiler.js:22709)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileTemplate (compiler.js:22696)
    at compiler.js:22639
    at Set.forEach (<anonymous>)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileComponents (compiler.js:22639)
    at compiler.js:22549
    at Object.then (compiler.js:206)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:22548)

**Comment by mariohmol** [comment]
hi.. i updated the stackblitz with new version 

https://stackblitz.com/edit/ang-jsoneditor?file=package.json

still working..

maybe recheck if u did what tells on https://github.com/mariohmol/ang-jsoneditor readme... or look in this stackblitz and see if u find anything u forgot. .. or post the code

**Comment by LanceJensen-Teradata** [comment]
Thanks for your response.  So from the stack trace it looks like it is trying to bind "data" and "options" but those fields do not exist due to some type of missing export of the module features. Here are excerpts of all the updates I made:

1. package.json:
...
"dependencies":{
...
"jsoneditor": "^5.34.0",
"ang-jsoneditor": "^1.7.7",
...
}

2. app.module.ts:
...
// JSON Editor module for dataset management
import { NgJsonEditorModule } from 'ang-jsoneditor'
...
@NgModule({
  imports: [
    ...
    NgJsonEditorModule
  ],...
})
export class AppModule {}

3. custom-dataset.component.html:
...

        	<json-editor [options]="editorOptions" [data]="dataSetJson" #editor></json-editor>
...

4. custom-dataset.component.ts:
...
// New JSON Editor Import
import { JsonEditorComponent, JsonEditorOptions } from 'ang-jsoneditor';
...
export class CustomDatasetComponent implements OnInit {
...
    public editorOptions: JsonEditorOptions;
    public dataSetJson: any;
    @ViewChild('editor') editor: JsonEditorComponent;

    public constructor(...) {
        this.editorOptions = new JsonEditorOptions();
    	this.initEditorOptions(this.editorOptions);
	this.dataSetCreated = false;
    }

    ngOnInit() {
        this.dataSetJson = {
             'trigger.file':null,
             'data.file': null
        };
    }

    ...
   saveDataSet(): void {
        ...
        const changedJson = JSON.stringify(this.editor.get());
        ...
   }
}

Thanks for your support.  Again this is likely a skill level thing on my part so any help would be appreciated.

**Comment by LanceJensen-Teradata** [comment]
Just as a follow on comment it seems to be trying to load your demo page in the stack trace... Is there some way to exclude the demo from the package?  Would that be to just delete it from the repo on disk and then rebuild and save the module again?

**Comment by mariohmol** [comment]
u might have to add in `NgJsonEditorModule ` in your shared.module

**Comment by mariohmol** [comment]
```[ERROR ->]<json-editor [options]="editorOptions" [data]="dataSetJson" #editor>
<!-- <"): ng:///SharedModule/CustomDatasetComponent.html@24:9```  your `CustomDatasetComponent` is on sharedmodule right?

**Comment by mariohmol** [comment]
on npm directory i do no send the mode files.. did u fork this project or u did the `npm i ang-jsoneditor` ?

**Comment by mariohmol** [comment]
try to see in your node_modules/ang-jsoneditor.. the demo file is not there

**Comment by LanceJensen-Teradata** [comment]
I cloned it to my local host.  Afterwards I built it and did ng serve to test the UI to see if it was what I wanted.  I was satisfied. I ran the following npm command:

 npm install --save jsoneditor ang-jsoneditor

Then I updated my project with the code changes above assuming that the code was being source from some local npm repo.

**Comment by LanceJensen-Teradata** [comment]
I inspected the node_modules/ang-jsoneditor and I did not see the demo classes so that must not be an issue.  I am unsure on how to add the shared.module can you advise on what to do?

**Comment by mariohmol** [comment]
try to remove the node_modules and install again.. the local fork of this project might be an issue.. 
search for shared.module.ts and add on import.. the same u did on app.modules.ts

**Comment by LanceJensen-Teradata** [comment]
I performed the update to add the import to the shared.module.ts. That changed the error messaging to the one below.  I will try exporting the NgJsonEditorModule from the shared module to see if that will resolve the template access issue:

Can't bind to 'options' since it isn't a known property of 'json-editor'.
1. If 'json-editor' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'json-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("com/mariohmol/ang-jsoneditor/blob/master/src/app/demo/demo.component.html -->
        	<json-editor [ERROR ->][options]="editorOptions" [data]="dataSetJson" #editor></json-editor>
            
        	<json-editor [options]="editorOptions" [ERROR ->][data]="dataSetJson" #editor></json-editor>
            
        	[ERROR ->]<json-editor [options]="editorOptions" [data]="dataSetJson" #editor></json-editor>
            <!-- <"): ng:///SharedModule/CustomDatasetComponent.html@24:9
    at syntaxError (compiler.js:215)
    at TemplateParser.push../node_modules/@angular/compiler/fesm5/compiler.js.TemplateParser.parse (compiler.js:14702)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._parseTemplate (compiler.js:22709)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileTemplate (compiler.js:22696)
    at compiler.js:22639
    at Set.forEach (<anonymous>)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileComponents (compiler.js:22639)
    at compiler.js:22549
    at Object.then (compiler.js:206)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:22548)

**Comment by LanceJensen-Teradata** [comment]
So after updating the shared.modules.ts file to add the import statement and then updating @NgModules to both import and export NgJsonEditorModule the errors where resolved and the editor displayed but with the following look and feel.  I think I need to do some manual import of your css assets into the module.  I will let you know if that fixes my issue but I am optimistic.  Thanks for your support.

![Screen Shot 2019-06-12 at 12 54 07 PM](https://user-images.githubusercontent.com/45405720/59374542-adb82e00-8d11-11e9-9345-aaedf5f602c4.png)

**Comment by LanceJensen-Teradata** [comment]
So I added the following import to the scss file:
@import "~jsoneditor/dist/jsoneditor.min.css";

With that change I still get the image shown above.  Can you advise on next steps?

**Comment by LanceJensen-Teradata** [comment]
So I think I should create a new issue because the module is loading now even if the styles and image assets are not...

**Comment by mariohmol** [comment]
see if that is erros on consol

**Comment by mariohmol** [comment]
this import should be on `style.css`
