### ISSUE TITLE
Unable to set a schema or enforce schema validation.

### ISSUE THREAD

**Issue by tar565** [mariohmol/ang-jsoneditor#43]
Am hoping to use the editor in an Angular 7 application to validate JSON. The JSON data is appearing in the editor but I am unable to assign a schema against which I can validate the JSON. I've tried the below in my .ts file but the validation does not kick in and no errors appears either.

this.editorOptions.schema = this.mySchemaAsJson
this.editor.setSchema(this.mySchemaAsJson)

**Comment by mariohmol** [comment]
Hi... can u provide a working example using jsoneditor?

i checked here on the ang-jsoneditor and we have the setSchema mapped.. and we are passing this to the real editor.. 

so maybe is how you have the `this.mySchemaAsJson`

or try to provide an example of this using this as starting point https://stackblitz.com/edit/ang-jsoneditor

**Comment by tar565** [comment]
Hi there, I got this working, following the example attached. Was initialising the editOptions in ngOnInit() originally and then setting the this.editorOptions.schema after a button click, which is only enabled after some other validation conditions are met. The schema was not getting set correctly at that point but on setting it in the ngOnInit(), along with the this.data, all worked fine.

**Comment by mariohmol** [comment]
awesome!! thanks for answering

**Comment by bikash-singh01** [comment]
https://stackblitz.com/edit/ang-jsoneditor

Do this example work? I changed one parameter lets say "id" to "i" but I get no error.

**Comment by mariohmol** [comment]
Wel, I think it works, what u are trying to do that its not working? share in stackblitz

**Comment by bikash-singh01** [comment]
I am looking for a way to provide schema to the jsoneditor using which the json text in the editor will be verified.
for example if my schema is 

```
{
  "type": "object",
  "properties": {
      "name": {
          "type": "string"
       }
   }
}
```

Then if I put a JSON as 
```
{
  "nam" :  "Bikash"
}
```

It should give an error saying 
"Hey nam is not valid key" or somthing like that

**Comment by bikash-singh01** [comment]
Hey @mariohmol, its working fine. Issue on my part.
For anyone who stumble across, what i learned from my mistakes

1. Check the version of the jsoneditor and ang-jsoneditor
2. additionalProperties is important part of jsonSchema 
3. verify if you are setting schema correctly in the options

**Comment by mariohmol** [comment]
thanks for sharing @bikash-singh01
