### ISSUE TITLE
Error editing data

### ISSUE THREAD

**Issue by pengsoftdotcom** [mariohmol/ang-jsoneditor#48]
The editor display as below.
![image](https://user-images.githubusercontent.com/32784811/60473183-929c6680-9c9e-11e9-8710-93632599a12f.png)
![image](https://user-images.githubusercontent.com/32784811/60473196-a1831900-9c9e-11e9-949c-e862057a83d8.png)
The "type" is a string, but not rendered right, and after I clicked on the checkbox,  an error occurred, "TypeError: VanillaPicker is not a constructor".
After clicked on the "batch" checkbox, the editor displayed an unknown JSON data, and an error occurred, "TypeError: Cannot read property 'length' of null".
![image](https://user-images.githubusercontent.com/32784811/60473370-603f3900-9c9f-11e9-8031-e94ddc071d26.png)

**Comment by mariohmol** [comment]
HI!!

I think in that case is a bug on jsoneditor itself.. 

could u please check it out here?  https://github.com/josdejong/jsoneditor
