### ISSUE TITLE
Change default language

### ISSUE THREAD

**Issue by KevinDebeil** [mariohmol/ang-jsoneditor#49]
Hello,

I try to change default language this way, but it doesn't works : 

this.editorOptions.language = 'pt-BR';

Please let me know if there's something I am overlooking.

**Comment by mariohmol** [comment]
Hi there.. indeed using the stackblitz example i can change the default mode.. and it shows changing.. but for language it does not change.. we have to investigate this feature on jsoneditor and see if is working properly

here is the stackblitz 

https://stackblitz.com/edit/ang-jsoneditor?file=src%2Fapp%2Fapp.component.ts
