### ISSUE TITLE
Missing 'templates' option in JsonEditorOptions

### ISSUE THREAD

**Issue by Axinet** [mariohmol/ang-jsoneditor#57]
**Describe the bug**
It looks like the 'templates' option is missing in the JsonEditorOptions class. It allows preparing predefined JSON parts to be easily inserted.

**Expected behavior**
JsonEditorOptions should have templates field allowing to set an array of "buttons" (text, title, className, field, value: any )

**Screenshots**
Screen from JSONEditor options linked from README.
![json-editor-settings](https://user-images.githubusercontent.com/393549/71267604-51cb0380-234b-11ea-9712-a7727cee8876.png)

**Comment by Axinet** [comment]
As whole settings object is forwarded to the underlying library, as for know it can be tricked with the following code:
`let editorOptions: JsonEditorOptions = new JsonEditorOptions();
(<any>this.editorOptions).templates = [{menu options objects as in json editor documentation}]`

**Comment by mariohmol** [comment]
Thanks @Axinet I included this workaround on the readme

the v1.9.0 includes this template and #58
