### ISSUE TITLE
Angular 9 support?

### ISSUE THREAD

**Issue by B1ll1** [mariohmol/ang-jsoneditor#59]
Do you intend to update the library so it supports angular 9?

**Comment by mariohmol** [comment]
yes.. if u can help out =)

**Comment by B1ll1** [comment]
@mariohmol I guess that this is it https://github.com/mariohmol/ang-jsoneditor/pull/60

I ran the tests and also played a bit using the local server and eveything seems to be working.

**Comment by zkozniak** [comment]
Please make it work, i need that too 🙏

**Comment by micahkaminer** [comment]
I would like to see it too, please....

**Comment by mariohmol** [comment]
cool let me check

**Comment by mariohmol** [comment]
thanks to @B1ll1 .. released on 1.9.2
