### ISSUE TITLE
Unable to use the component

### ISSUE THREAD

**Issue by syerrawa** [mariohmol/ang-jsoneditor#6]
Got below error when followed the directions to import in angular 5

ERROR in ./node_modules/ang-jsoneditor/esm5/ang-jsoneditor.js
Module not found: Error: Can't resolve 'jsoneditor' in '/Users/syerrawa/Workspace/cisco-components/node_modules/ang-jsoneditor/esm5'
resolve 'jsoneditor' in '/Users/syerrawa/Workspace/cisco-components/node_modules/ang-jsoneditor/esm5'
  Parsed request is a module

**Comment by syerrawa** [comment]
Cool. That solved the problem. It was not mentioned in the README.md
May be you can include that in your package.json so we get it automatically
we do just do


npm install --save ang-jsoneditor
<https://github.com/mariohmol/ang-jsoneditor#usage>

**Comment by mariohmol** [comment]
updated!! thanks

**Comment by mariohmol** [comment]
the dependency is included in package json.. 

https://github.com/mariohmol/ang-jsoneditor/blob/master/package.json#L27
https://github.com/mariohmol/ang-jsoneditor/blob/master/ang-jsoneditor/package.json#L21

so i dont know what else i could change to be automaticaly

**Comment by syerrawa** [comment]
I see that it is in the peerDependencies. If you put it in the regular dependencies then it would be packaged as part of your bundle.

**Comment by mariohmol** [comment]
There is an bug about this.. i cant remember where is the issue.. i had to use peer instead of dependency.. when it compiles the ang-jsoneditor to not include jsoneditor .. instead this will break when u try to import to your project

**Comment by syerrawa** [comment]
Hmm. Interesting. Ok then. I guess its fine since you already took care of
updating the README.MD. Thanks for being so active and immediate.
Appreciate it.

Take it easy and Have a great weekend ahead!!

**Comment by syerrawa** [comment]
Hi Mario,

Was wondering how I can access the modified JSON. Lets say I edited the JSON in Tree view how can I get the new modified JSON?

Thanks,
Sachin.

**Comment by mariohmol** [comment]
Good question.. updated the demo app

https://github.com/mariohmol/ang-jsoneditor/blob/master/src/app/demo/demo.component.ts#L79
