### ISSUE TITLE
Is this possible to add drop-down inside this editor?

### ISSUE THREAD

**Issue by AjasAju** [mariohmol/ang-jsoneditor#63]
Let's say you want to force "primary_color" to be one of the colors in the colours array. How to tell JSON Editor that we want to use this field to populate a dropdown..

**Comment by AjasAju** [comment]
Finally  I got the answer,

        @ViewChild(JsonEditorComponent, { static: true }) editor: JsonEditorComponent;
        this.editorOptions = new JsonEditorOptions()
        this.editorOptions.modes = ['code', 'text', 'tree', 'view']; 
        this.editorOptions.expandAll = true;
        this.editorOptions.schema ={
      'definitions': {},
      '$schema': 'http://json-schema.org/draft-07/schema#',
      '$id': 'http://example.com/root.json',
      'type': 'object',
      'title': 'Product Attributes',
      'required': [
        'property'
      ],
      'properties': {
        'property': {
          '$id': '#/properties/randomNumber',
          'type': 'string',
          'title': 'Attribute property',
          'default': 'Configurable',
          'examples': [
            'Configurable'
          ],
          'enum': ['Configurable','Simple']
        }
      }
    }

I have added a JSON schema with the help of `new JsonEditorOptions()` and set the dropdown values using `Enum` keyword ` 'enum': ['Configurable','Simple']`. Now it will appear inside a select dropdown list.

And you can read the Json editor value in the `onChangeJSON `

      this.editorOptions.onChangeJSON = function () {
         const json = this.editor.get();   
         console.log(json);
      };

**Comment by mariohmol** [comment]
AWESOME!!!

Thank you for this, will be useful for other users.

Thanks!
