### ISSUE TITLE
Accessor cannot be declared in ambient context

### ISSUE THREAD

**Issue by subtletale** [mariohmol/ang-jsoneditor#65]
**Describe the bug**
On running an AOT production build in angular 7, getting a compile error of 'An accessor cannot be declared in ambient context' from line 13 in the jsoneditor.component.d.ts file.

**To Reproduce**
In your terminal, run the following commands on an angular 7 project:
npm install ang-jsoneditor@1.9.2
ng build --prod

**Expected behavior**
build should compile as usual

**Console and Error stack trace**
see images below

**Screenshots**
![image](https://user-images.githubusercontent.com/44418715/81229637-2412ee00-8fbe-11ea-9f3b-b7efbcd2cae3.png)

![image](https://user-images.githubusercontent.com/44418715/81229709-4278e980-8fbe-11ea-8a50-0bf7dd293b40.png)

**Desktop (please complete the following information):**
 - OS: Mojave 10.14.6
 - Chrome
 - Angular CLI: 7.3.10
Node: 8.17.0
OS: darwin x64
Angular: 7.2.16
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.10
@angular-devkit/build-angular     0.13.10
@angular-devkit/build-optimizer   0.13.10
@angular-devkit/build-webpack     0.13.10
@angular-devkit/core              0.7.5
@angular-devkit/schematics        7.3.10
@angular/cdk                      7.3.7
@angular/cli                      7.3.10
@ngtools/webpack                  7.3.10
@schematics/angular               7.3.10
@schematics/update                0.13.10
rxjs                              6.5.5
typescript                        3.2.4
webpack                           4.29.0

**Additional context**
v1.9.1 of this package does not use the 'set' keyword for the data property picture in the image above, line 13, which seems to be the issue here.

**Comment by subtletale** [comment]
Some additional feedback from a coworker pointed out that the version of typescript we have is lower than what 1.9.2 has. He tested with a clean angular 7 project, installed ang-jsoneditor@1.9.2, and was able to reproduce the error. It would seem that 1.9.2 relies on a higher typescript version, and angular 7 requires typescript < 3.3  -  so basically 1.9.2 won't work on an angular 7 project.

**Comment by subtletale** [comment]
Seems this is actually an issue on Typescript, some further reading on the problem: https://github.com/microsoft/TypeScript/issues/33939

**Comment by mariohmol** [comment]
good investigation here!!

Any ideas on how to solve this?

**Comment by mariohmol** [comment]
maybe try to use an older version that is compatible with ang7? 

like 1.7.8

**Comment by thedarkvessle** [comment]
rolling back to version "1.9.0", resolved this issue for me  with ts version 3.1.6

**Comment by mariohmol** [comment]
There is a new release for this that works with ang10, could you please test this?
