### ISSUE TITLE
Unsupported options 'schemaRefs' and 'onValidationError'

### ISSUE THREAD

**Issue by davebaol** [mariohmol/ang-jsoneditor#66]
**Is your feature request related to a problem? Please describe.**
Peer dependency from jsoneditor is outdated and  both options `schemaRefs` and  `onValidationError` are not supported by `JsonEditorOptions`

**Describe the solution you'd like**
- In peer dependencies use jsoneditor ^8.6.8
- Add support for options `schemaRefs` and  `onValidationError`

**Describe alternatives you've considered**
I could extend `JsonEditorOptions` with missing options and pass that instance to the component.
Looks like it works, but I'm not sure about possible drawbacks. Also it sounds like a hack.

**Comment by davebaol** [comment]
Also, after updating peer dependencies to jsoneditor ^8.6.8
```typescript
  public setSchema(schema: any) {
    this.editor.setSchema(schema);
  }
```
should become
```typescript
  public setSchema(schema: any, schemaRefs: any) {
    this.editor.setSchema(schema, schemaRefs);
  }
```

**Comment by RondoK** [comment]
@davebaol  You can get access to onValidationError via "brackets property access"

`this.editorOptions["onValidationError"] = (errors: object[ ]) : void =>
    {
YOUR_CODE_HERE
    }`

**Comment by mariohmol** [comment]
added this in the latest.. thanks
