### ISSUE TITLE
Question: how to get all change response in ang-jsoneditor? (change) emits only if the change is valid.

### ISSUE THREAD

**Issue by codepillar91** [mariohmol/ang-jsoneditor#67]
`<div *ngFor="let workflow of vm.workflows">`
`<h3>workflow.workflowId</h3>`
`<json-editor (change)="onChange($event)" [options]="makeOptions()" [data]="workflow.Config">`         `</json-editor>`
`</div>`

Is it possible to get a event fired up whenever any change happens in the json irrespective of it's validation?

**Comment by RahulRazdan** [comment]
have you tried
this.editorOptions.onChange ?

**Comment by codepillar91** [comment]
Yes I tried that. Limitation with this.editorOptions.onChange is, i can't get any additional info as this is a void property. So in my case i have multiple editors in a view and i can't differentiate for which the onChange is getting called. 

Do you have any suggestion for that? @RahulRazdan

**Comment by mariohmol** [comment]
You can build different functions for each editor,  and those functions will call a main function that does what you plan to do...

no?

**Comment by mariohmol** [comment]
Feel free to reopen if still a problem
