### ISSUE TITLE
How can we implement autocomplete feature for fields value. 

### ISSUE THREAD

**Issue by RahulRazdan** [mariohmol/ang-jsoneditor#69]
jsoneditor has a lot of examples for autocomplete
https://github.com/josdejong/jsoneditor/blob/develop/examples/11_autocomplete_basic.html

But I do not see any option for autocomplete on editorOptions or editor itself.

Is it possible to have autocomplete for value fields? The idea is while use type value in field I should provide autocomplete using rest API.

Thanks in advance. :)

**Comment by mariohmol** [comment]
Hi, try to see if this discussion helps you

https://github.com/mariohmol/ang-jsoneditor/issues/70

**Comment by mariohmol** [comment]
Feel free to reopen if u need
