### ISSUE TITLE
Angular 10 support

### ISSUE THREAD

**Issue by timmyrosen** [mariohmol/ang-jsoneditor#72]
Can we expect support for angular 10?

As of now, when serving or building the application I get the following error:
```bash
ERROR in node_modules/ang-jsoneditor/lib.module.d.ts:3:23 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).
static forRoot(): ModuleWithProviders;
```

Thanks for a great plugin btw, really useful!

**Comment by loedeman** [comment]
Workaround: when getting the plugin from NPM (not building yourself), the plugin works fine with Angular 10.

**Comment by mariohmol** [comment]
Hi guys.. bumped a releae for ang 10

ang-jsoneditor@1.10.0

double check pls if is working
