### ISSUE TITLE
Error in onChange callback:  Error: Parse error on line

### ISSUE THREAD

**Issue by MariaZarapuz** [mariohmol/ang-jsoneditor#75]
Hello, I have seen in the demo of your library that it brings out this warning by console, I have implemented your library in my project and the same thing is happening to me. Is there any way to remove that warning by console? Thank you.

<img width="1092" alt="Captura de pantalla 2020-09-22 a las 17 45 37" src="https://user-images.githubusercontent.com/56505900/93905615-7483b180-fcfb-11ea-9a18-e02ed063f87d.png">

**Comment by mariohmol** [comment]
Hi! What demo is giving you this error? I dont see on my side

**Comment by MariaZarapuz** [comment]
https://stackblitz.com/edit/ang-jsoneditor?file=src%2Fapp%2Fapp.component.ts

**Comment by mariohmol** [comment]
did u make any action do make this error? did u change the code?

because here is fully working.. mabye try to open in a incognito window

**Comment by MariaZarapuz** [comment]
It happens when the json is not valid, it sends me this error by console.

Try to delete the json and it will appear

**Comment by mariohmol** [comment]
please provide a stackblitz example with this error

**Comment by MariaZarapuz** [comment]
<img width="2880" alt="Captura de pantalla 2020-09-22 a las 18 05 08" src="https://user-images.githubusercontent.com/56505900/93907940-4c498200-fcfe-11ea-9cfa-ca0172dee968.png">

**Comment by mariohmol** [comment]
This is expected if u remove the quotes and have a Json in a bad format

**Comment by mariohmol** [comment]
this is coming from json-editor , maybe check there if is an issue about it

**Comment by MariaZarapuz** [comment]
Yes, but there is no way that this message does not appear in the console. Since the visual warning works for me.

**Comment by mariohmol** [comment]
I see .. that makes sense.. check the v1.10.2 , now if u have the debug with true he will console.log the error.. if not will be clear!

**Comment by MariaZarapuz** [comment]
Where can I find version 1.10.2?

**Comment by mariohmol** [comment]
just released now.. install the library again

**Comment by MariaZarapuz** [comment]
Hello I have tried version 1.10.2 and it changes the site failure in case it is my fault
<img width="2880" alt="Captura de pantalla 2020-09-22 a las 18 53 54" src="https://user-images.githubusercontent.com/56505900/93913268-1fe53400-fd05-11ea-9779-3cfa3abc842c.png">

**Comment by mariohmol** [comment]
this is old version.. u can see that in stackblitz is not giving error anymore

**Comment by MariaZarapuz** [comment]
Thank you very much for your attention and speed, I have already managed to integrate it without receiving that error.

**Comment by MariaZarapuz** [comment]
Hi, I'm sorry to bother you, but I'm seeing that now I call the change () function and it only sends me something if the json is fine, and I don't know how I try to validate the json by not receiving anything when it's wrong

**Comment by mariohmol** [comment]
There is no way to make it return a json if is not valid, sorry, it will send u the json as soon as the user make the json correct
