### ISSUE TITLE
The target entry-point "ang-jsoneditor" has missing dependencies:  - jsoneditor

### ISSUE THREAD

**Issue by gnvsvarma** [mariohmol/ang-jsoneditor#77]
**Describe the bug**
after installing i am trying to add module , then i am getting below 
**ERROR in The target entry-point "ang-jsoneditor" has missing dependencies:
 - jsoneditor**

Angular version
------------------

@angular-devkit/architect         0.901.6
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              9.1.6
@angular-devkit/schematics        9.1.6
@angular/animations               9.1.9
@angular/cdk                      9.2.4
@angular/cli                      9.1.6
@angular/material                 9.2.4
@ngtools/webpack                  10.0.8
@schematics/angular               9.1.6
@schematics/update                0.901.6
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.43.0

**Comment by mariohmol** [comment]
does `npm i jsoneditor` works?

**Comment by mariohmol** [comment]
This is in the installation docs, if does not work feel free to open again

**Comment by rawatravi** [comment]
npm install --save jsoneditor ang-jsoneditor work for me

**Comment by nooranshah** [comment]
npm install --save jsoneditor ang-jsoneditor work me thanks @rawatravi
