### ISSUE TITLE
Which version of jsoneditor?

### ISSUE THREAD

**Issue by thatcort** [mariohmol/ang-jsoneditor#80]
The root package.json lists the jsoneditor version as `^8.3.0`, but in the deployed library it requires a peer of `^7.0.2`. jsoneditor is now up to `9.1.8`. Which version is best?

**Comment by mariohmol** [comment]
good question.. this was tested using 8x... i can deploy a new release soon testing in 9x

**Comment by thatcort** [comment]
Cool. Then also update the version number in ang-jsoneditor/ang-jsoneditor/package.json, since that's the one that consumers will see.

**Comment by thatcort** [comment]
I just tested the latest version of jsoneditor on Angular 11 and at first glance it looks fine.

**Comment by Sparksx** [comment]
🆙

**Comment by mariohmol** [comment]
cool.. thanks for this testing guys..
released on v1.10.5
