### ISSUE TITLE
How to validate, array only allow one value which is present in schema.

### ISSUE THREAD

**Issue by PParshive** [mariohmol/ang-jsoneditor#81]
Hi,
From given schema :
		"properties": {
				"resultType": {
					"$id": "#root/ruleProperties/resultType", 
					"title": "Resulttype", 
					"type": "array",
					"contains": {"type": "string"},
					"default": [],
					"items":{
						"$id": "#root/ruleProperties/resultType/items", 
						"title": "Items", 
						"type": "string",
						"default": "",
						"enum":["expression","rowcount"],
						"examples": [
							"expression"
						]
					}
				}
Array : "resultType":["expression"] 
resultType array should allow either "expression" or "rowcount", can you guys tell me how to achieve this feature?.

Thanks

**Comment by mariohmol** [comment]
uhmm I dont know.. as this is a wrapper for json-editor, I would say to look at that repo  https://github.com/josdejong/jsoneditor
