### ISSUE TITLE
Enable Lazy loading as a component

### ISSUE THREAD

**Issue by stalsma-palmetto** [mariohmol/ang-jsoneditor#85]
**Is your feature request related to a problem? Please describe.**
I'm using this module as as convenience for viewing json that is usually simply consumed by more-frequented portions of the application.  It will be rare that most users ever see the module that uses jsoneditor.

I've configure my admin module to lazy load, and inside that module, I lazy-load json-editor.

```
  /**
   * dynamically loads json-editor module
   */
  async loadEditor(): Promise<any> {

    this.editorContainerRef.clear();
    const {JsonEditorComponent} = await import('ang-jsoneditor');
    const editorFactory = this.cfr.resolveComponentFactory(JsonEditorComponent);
    const editor: ComponentRef<any> = this.editorContainerRef.createComponent(editorFactory, undefined, this.injector);

    editor.instance.options = {
      modes: ['code', 'text', 'tree', 'view'], // set all allowed modes
      mode: 'code',
      language: 'en'
    };
    editor.instance.data = this.entity!.jsonData;
  }
```

Everything works fine, but I see the hit to load the module immediately on app startup.  800k that most users will never see.

**Describe the solution you'd like**
The code first be downloaded when the route that accesses the editor requested.

**Describe alternatives you've considered**
I've considered trying to load as a lazy-module, using essentially a dummy child route into which I redirect, e.g.

> feature/:id/details/load-editor

But that seems convoluted.

Since I am accessing it only in a lazy-loaded module, I've also tried only importing it into that feature module.  But the behavior remains the same.  My app loads (and I immediately take the hit for /app/npm.jsoneditor.d949bfd490f05da2f72a.chunk.js.  Then I navigate to my lazy-loaded feature module (which does correctly lazy load, but weighs significantly less than the jsoneditor).

**Additional context**
Using angular 10, and ang-jsoneditor 1.10.5

**Comment by mariohmol** [comment]
Hi, thanks!

Any suggestions on how to fix this?

**Comment by stalsma-palmetto** [comment]
I suspect that the problem is the call to forRoot() in the module definition.

> As of right now, it's not possible to execute a forRoot (or any other configuration static method of this sort) in a module that will load lazily. The problem here is that such a method returns a ModuleWithProviders while loadChildren requires a NgModuleFactory. [1]

So it would seem we need to also implement *forChild()* and return *NgModuleFactory* there.  I found a nice example of doing both w/in a single module[2].

But does correctly implementing *forChild* suffice to ensure lazy loading?  I'm admittedly a bit out of my depth.

[1] https://stackoverflow.com/questions/48601849/angular-lazy-load-does-not-work-when-invoking-forroot#:~:text=As%20of%20right%20now%2C%20it's,while%20loadChildren%20requires%20a%20NgModuleFactory%20.

[2] https://www.freelancermap.com/blog/using-forroot-and-forchild-to-configure-modules-in-angular/

**Comment by stalsma-palmetto** [comment]
I went about trying to fix this myself, and in doing so, confirmed that lazy loading the component does actually work in a minimum project.  I don't understand why it doesn't work in my larger project, but that's another issue.

For reference, if the following component is loaded by the application, it will lazy-load json-editor.

```
import {Component, ComponentFactoryResolver, ComponentRef, Injector, OnInit, ViewChild, ViewContainerRef} from '@angular/core';

@Component({
  selector: 'app-foo',
  templateUrl: './foo.component.html',
  styleUrls: ['./foo.component.scss']
})
export class FooComponent implements OnInit {
  public data: any;
  @ViewChild('editor', {read : ViewContainerRef}) editor!: ViewContainerRef;

  constructor(private cfr: ComponentFactoryResolver,
              private injector: Injector) {

    this.data = {
      products: [{
        name: 'car',
        product: [{
          name: 'honda',
          model: [{id: 'civic', name: 'civic'}, {id: 'accord', name: 'accord'}, {id: 'crv', name: 'crv'}, {
            id: 'pilot',
            name: 'pilot'
          }, {id: 'odyssey', name: 'odyssey'}]
        }]
      }]
    };
  }

  ngOnInit(): void {
    this.loadEditor();
  }

  private loadEditor(): void {
    import('ang-jsoneditor')
      .then(({JsonEditorComponent}) => {
      const EditorFactory = this.cfr.resolveComponentFactory(JsonEditorComponent);
      const editor: ComponentRef<any> = this.editor.createComponent(EditorFactory, undefined, this.injector);
      editor.instance.data = this.data;
    } );
  }
}
```
