### ISSUE TITLE
Automatically curly brackets added end of JSON while running through selenium automation testing.

### ISSUE THREAD

**Issue by PParshive** [mariohmol/ang-jsoneditor#86]
Automatically curly brackets added end of JSON while running through selenium automation testing.

**Expected behavior**
Curly brackets is not added end of JSON while running through selenium automation testing.

```html
  <json-editor id="jsonTemplate" #editor [options]="options" autofocus="autofocus"
                        (keydown)="isDefault ? $event.preventDefault() : ''"
                        [formControl]="complexForm.controls['jsonTemplate']" autofocus
                        value="{{complexForm.controls['jsonTemplate']}}" onfocus="this.value = this.value;"
                        (change)="changeLog($event)"></json-editor>
```

**Screenshots**
![Screenshot (69)_LI](https://user-images.githubusercontent.com/75675307/113887165-e676a080-97de-11eb-83bf-3bab2cb53b09.jpg)

**Version**
"ang-jsoneditor": "^1.10.3",
 "jsoneditor": "5.19.2"

Its not create a problem while manually. Only through automation got the behavior.

**Comment by mariohmol** [comment]
Any idea in what can cause it?

DId u test the same dataset with pure angjson editor? maybe its a bug on the core and not in the angular wrapper

**Comment by mariohmol** [comment]
Try to use this way instead `[value]="complexForm.controls['jsonTemplate']"`
