### ISSUE TITLE
Not able to copy JSON in disabled JSON editor.

### ISSUE THREAD

**Issue by PParshive** [mariohmol/ang-jsoneditor#87]
**Describe the bug**
I want to copy the JSON from disabled JSON editor but copy option is not available in open panel when right click after selecting JSON.

**To Reproduce**
1. Create a disabled JSON editor from below code.
2. Select the entire JSON from mouse and right click.
3. Many option is available but there is no copy option.

**Expected behavior**
Copy option should be availble.

**Console and Error stack trace**

**css** 
#jsonTemplate.disable-json div.jsoneditor{
    .jsoneditor-menu{
        .jsoneditor-modes{
            button{color:#888}
        }
    }
    .jsoneditor-outer{ opacity:0.6;
        .ace_editor{
            .ace_gutter{background:#dedede;}
            .ace_scroller{ background:#f4f4f4 !important;
            pointer-events: none;}
        }
    }
}

**ts** 
document.getElementById('jsonTemplate').classList.add('disable-json');

**html**
 <json-editor id="jsonTemplate" #editor [options]="options" autofocus="autofocus"
                        (keydown)="isDefault ? $event.preventDefault() : ''"
                        [formControl]="complexForm.controls['jsonTemplate']" autofocus
                        value="{{complexForm.controls['jsonTemplate']}}" onfocus="this.value = this.value;"
                        (change)="changeLog($event)"></json-editor>

**Screenshots**
![Screenshot (73)](https://user-images.githubusercontent.com/75675307/114887722-53fd7f00-9e26-11eb-954a-ca44f3d68173.png)

**Desktop:**
 - Browser [chrome]
 - Ng Version [  "jsoneditor": "5.19.2", "ang-jsoneditor": "^1.10.3",]

**Additional context**
If you have any solution to add copy option in a panel then please provide a solution. Otherwise give me any other solution to full fill my requirement. 
Only I want to copy the JSON from disabled JSON editor.

Thank you !

**Comment by mariohmol** [comment]
You can create a button to copy to the clipboard the generated json
