### ISSUE TITLE
ViewChild(JsonEditorComponent) editor: JsonEditorComponent returns undefined

### ISSUE THREAD

**Issue by neil-coutinho** [mariohmol/ang-jsoneditor#9]
`import { Component, OnInit, Input, ViewChild } from '@angular/core';
import { JsonEditorComponent, JsonEditorOptions } from 'ang-jsoneditor';

@Component({
  selector: 'app-code-view',
  templateUrl: './code-view.component.html',
  styleUrls: ['./code-view.component.scss']
})
export class CodeViewComponent implements OnInit {
 public editorOptions: JsonEditorOptions;
 @ViewChild(JsonEditorComponent) editor: JsonEditorComponent;

  constructor() {

    this.editorOptions = new JsonEditorOptions();
    console.log('editorOptions', this.editorOptions);
    console.log('editor', this.editor); => UNDEFINED?
    this.editor.setOptions(this.editorOptions);
   }

  ngOnInit() {

  }

}
`

@mariohmol any idea why this.editor logs as undefined? Also this this.editorOptions.ace deprecated?

**Comment by mariohmol** [comment]
Do you have `<json-editor [options]="editorOptions" [data]="data" ></json-editor>` in your html? an try to console log on `ngOnInit `

**Comment by neil-coutinho** [comment]
Yes I do. In my component html file code-view.component.html 

`<div class="jsoneditor-wrapper"><json-editor
    [options]="editorOptions"
    [data]="code">
</json-editor>
</div>`

**Comment by neil-coutinho** [comment]
Ok I am able to log the value in ngAfterViewInit().  

Any idea how can I configure the ace editor via setOptions() @mariohmol ?

**Comment by mariohmol** [comment]
Do you have any example of how use ace editor with jsoneditor?

**Comment by neil-coutinho** [comment]
![screen shot 2018-06-15 at 9 38 37 am](https://user-images.githubusercontent.com/33371261/41449675-2148b7f4-7080-11e8-8279-f497cde7f304.png)
![screen shot 2018-06-15 at 9 39 01 am](https://user-images.githubusercontent.com/33371261/41449676-217d037e-7080-11e8-8696-4ad1ce8fee3e.png)
@mariohmol I wanted to turn of the drag and reorder and change type features. Also according to the [Ace API Doc](https://github.com/ajaxorg/ace/wiki/Configuring-Ace) there are a number of config options can we use this by setting `this.editorOptions.ace = {}` ?

**Comment by mariohmol** [comment]
I see, the thing is , do you have and example with jsoneditor ( https://github.com/josdejong/jsoneditor ) applying this? Because this is just an angular wrapper.. so if it might need changes in jsoneditor i will not be able to help you =(

**Comment by mariohmol** [comment]
There is already an ace property to be configured:  https://github.com/mariohmol/ang-jsoneditor/blob/master/ang-jsoneditor/src/jsoneditor/jsoneditor.component.ts#L111
