### ISSUE TITLE
Warning: Option "onChangeJSON" is not applicable to modes "text" and "code".

### ISSUE THREAD

**Issue by TheGameKnave** [mariohmol/ang-jsoneditor#90]
The JsonEditorOptions object includes a property for onChangeJSON and whether it's set or not, a console warning is triggered if the modes array includes "text" or "code". I'm not using onChangeJSON so it's kind of bizarre to be getting that warning.

Option "onChangeJSON" is not applicable to modes "text" and "code". Use "onChangeText" or "onChange" instead.

**Comment by MasterAzazel** [comment]
getting same warning

**Comment by fgerges** [comment]
hope for a correction in 2023? that would be greatly appreciated, and thank you in advance.

**Comment by mariohmol** [comment]
Hi, this seems to be triggered by the jsoneditor component: 
https://github.com/josdejong/jsoneditor/blob/d0df2f4c383d8935df750c760a6e69deefa0ff14/src/js/JSONEditor.js#L137

If you think a way we can avoid it using the code for this wrapper, please let us know

**Comment by mariohmol** [comment]
thanks a lot @josdejong , will do it tonight

**Comment by mariohmol** [comment]
Thanks @josdejong , just released on v3.0.2
