### ISSUE TITLE
Not able to disable JSON editor.

### ISSUE THREAD

**Issue by SachinOjhaFD** [mariohmol/ang-jsoneditor#93]
**Describe the bug**
I want to disable the JSON editor but not able to disable it.

**To Reproduce**
Steps to reproduce the behaviour :

Create a JSON editor from below code.
<json-editor [options]="editorOptions">
</json-editor>
Many option is available but there is no disable option available.

**Expected behaviour.**
Disable option should be available.

**Laptop:**
Browser [chrome]
Ng Version [ "jsoneditor": "9.4.1", "ang-jsoneditor": "^1.10.5",]

**Additional context**
If you have any solution to disable JSON editor then please provide a solution.

Thank you !

**Comment by mariohmol** [comment]
Hi there, what u mean about disable option?

There is some mode on jsoneditor, check it out
https://github.com/josdejong/jsoneditor#tree-mode

Sorry but this is just a wrapper, any customization should on jsoneditor side
