### ISSUE TITLE
Angular 13 and Ivy support

### ISSUE THREAD

**Issue by fgoulet** [mariohmol/ang-jsoneditor#96]
When building our project with Angular 13, this message is displayed

 Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- ang-jsoneditor [es2015/esm2015] (git+https://github.com/mariohmol/ang-jsoneditor.git)

Encourage the library authors to publish an Ivy distribution.

**Comment by hardikpatel043** [comment]
@mariohmol Can we upgrade to Angular 13?

**Comment by puranjayjain** [comment]
We can upgrade to an ivy distribution for angular 13 native support and a faster build

**Comment by hardikpatel043** [comment]
https://www.npmjs.com/package/ang-json-editor-13

**Comment by mariohmol** [comment]
Thanks @hardikpatel043 , could you please provide a PR for us? thanks

**Comment by hardikpatel043** [comment]
https://github.com/mariohmol/ang-jsoneditor/pull/103

**Comment by RodolfoXDR** [comment]
Angular 14 now

**Comment by hardikpatel043** [comment]
@mariohmol can you please publish angular 13 version?

**Comment by mariohmol** [comment]
Thanks @hardikpatel043 

published as 2.0.1
