### ISSUE TITLE
JsonEditorOptions "onClassName" not having a node argument

### ISSUE THREAD

**Issue by HeyItsRoi** [mariohmol/ang-jsoneditor#99]
I am trying to find a way to add class names to each node when I'm in tree mode.
I'm assuming that the onClassName method in the JsonEditorOptions is just missing an argument

and instead of it being like this:
```js
    onClassName: () => string;
```

I would like it to be like this:
```js
    onClassName: (node: JsonEditorTreeNode) => string;
```

**Comment by mariohmol** [comment]
Accepted your PR, thank you!
